" ----------------------------------------------------------------------------
" Preface
" ----------------------------------------------------------------------------

" Remove all autocommands for the current group.
autocmd!

if ! empty($kw_goroot)
    set runtimepath+=$kw_goroot/misc/vim
endif

call pathogen#infect()

runtime ftplugin/man.vim

" ----------------------------------------------------------------------------
" Formatting
" ----------------------------------------------------------------------------

" To insert a real tab, use CTRL-V<Tab>

" In insert mode, use 'tabstop' spaces when inserting a <Tab>.
set expandtab

" Number of spaces displayed for <Tab>.
set tabstop=8

" Number of spaces to use for each step of (auto)indent.  Used for 'cindent',
" '>>', '<<', etc.
set shiftwidth=4

" With 'smarttab' on, <Tab> indents with 'shiftwidth'.  When off, a <Tab>
" indents with 'tabstop' or 'softabstop'.
set smarttab

set formatoptions=tcqn1


" ----------------------------------------------------------------------------
" Appearance
" ----------------------------------------------------------------------------

colorscheme kiwi_dark

"
" Highlights
"
set cursorline
set hlsearch


"
" Status Line
"
set laststatus=2  " Always display status line.
set showcmd
set ruler


"
" Misc
"
syntax on
set nowrap
set listchars=tab:>-,extends:%,precedes:%


" ----------------------------------------------------------------------------
" Mapc
" ----------------------------------------------------------------------------

let mapleader = ","

nnoremap <leader>erc :tabedit $MYVIMRC<cr>
nnoremap <leader>src :source $MYVIMRC<cr>

" In command mode, <ENTER> behaves the same as in WYSIWYG editors.
noremap <CR> o<ESC>
noremap <S-CR> O<ESC>

nnoremap K :Man <cword><cr>

nnoremap <leader>tb :TagbarToggle<cr>

nnoremap <leader>cp :CtrlP<cr>
nnoremap <leader>cpf :CtrlP<cr>
nnoremap <leader>cpb :CtrlPBuffer<cr>
nnoremap <leader>cpr :CtrlPMRU<cr>
nnoremap <leader>cpt :CtrlPTag<cr>

" ----------------------------------------------------------------------------
" Filetypes
" ----------------------------------------------------------------------------

" Automatically detect filetype, and load its plugin and indent file.
filetype plugin indent on

autocmd BufRead,BufNewFile *.l,*.lpp set filetype=lex
autocmd BufRead,BufNewFile *.scala set filetype=scala
autocmd BufRead,BufNewFile *.y,*.ypp set filetype=yacc

" Use standard formatting for PKGBUILD.
autocmd BufNewFile,BufRead PKGBUILD* set et ts=2 sw=2

" ----------------------------------------------------------------------------
" Misc
" ----------------------------------------------------------------------------

" Buffers remain open when hidden.
set hidden

" Don't leave litter lying around.
set nobackup
set nowritebackup
set noswapfile

" sessionoptions
"     - 'options' and 'localoptions' are mutually exclusive.
"     - 'sesdir' gives more predictable behavior thean 'curdir'.
set sessionoptions=buffers,folds,globals,help,localoptions,resize,tabpages,winpos,winsize

set backspace=indent,eol,start
set matchpairs+=<:>
set modeline
set mouse=
set spelllang=en_us
set visualbell
set wildmenu

" vim: et sw=4:
" The standard codestyle for PKGBUILD.
