kw_color_start='\e['
kw_color_end='m'

kw_color_reset='0'

kw_color_face_book='0'
kw_color_face_bold='1'
kw_color_face_ul='4'

kw_color_fg_black='30'
kw_color_fg_red='31'
kw_color_fg_green='32'
kw_color_fg_yellow='33'
kw_color_fg_blue='34'
kw_color_fg_purple='35'
kw_color_fg_cyan='36'
kw_color_fg_white='37'

kw_color_fg_hi_black='90'
kw_color_fg_hi_red='91'
kw_color_fg_hi_green='92'
kw_color_fg_hi_yellow='93'
kw_color_fg_hi_blue='94'
kw_color_fg_hi_purple='95'
kw_color_fg_hi_cyan='96'
kw_color_fg_hi_white='97'

kw_color_bg_black='40'
kw_color_bg_red='41'
kw_color_bg_green='42'
kw_color_bg_yellow='43'
kw_color_bg_blue='44'
kw_color_bg_purple='45'
kw_color_bg_cyan='46'
kw_color_bg_white='47'

kw_color_bg_hi_black='100'
kw_color_bg_hi_red='101'
kw_color_bg_hi_green='102'
kw_color_bg_hi_yellow='103'
kw_color_bg_hi_blue='104'
kw_color_bg_hi_purple='105'
kw_color_bg_hi_cyan='106'
kw_color_bg_hi_white='107'
