#!/bin/bash

set -eu

: ${XDG_CONFIG_HOME:=$HOME/.config}

cd "$GIT_DIR"

mkdir -p info
echo '*' >info/exclude

hooks="$XDG_CONFIG_HOME/vcsh/git-hooks.d/$VCSH_REPO_NAME"
if [[ ! -e "$hooks" ]]; then
    mkdir -p "$hooks"
fi
if [[ -e hooks ]]; then
    rm -r hooks
fi
ln -fs "$hooks" hooks
